# Site settings
author: Kaitlin Kelly
title: Coding By The Sea
header-img: img/home-bg.png
email: kk504408@gmail.com
copyright_name: Kaitlin Kelly
description: > # this means to ignore newlines until "baseurl:"
  If you can't blog about it to a 4 year old, do you really know it?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Kkelly22

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
