# Site settings
title: Coding by the Sea
header-img: img/home-bg.png
email: kk504408@gmail.com
copyright_name: Kkelly22
description: > # this means to ignore newlines until "baseurl:"
  Where logic meets creativity
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Kkelly22
learn_profile: Kkelly22
email_username: kk504408@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
